### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by kyleteeter**
# Description

This addition is a Landing page that will redirect to the User Logins. It is built as a react app in order to be easily expandable in to have scalable functionality. Right now it is the the basics but the structure can be found in the components and images in the assets file.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

No testing done yet.

# Checklist:

- [x ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by leeformento** [comment]
Is this the one ongoing with the merge conflict?

**Review by mmeitl — APPROVED** [review]
Approved!

**Review by travis-russell — APPROVED** [review]
Nice, let's see if those failed checks fix once merged

**Review by leeformento — APPROVED** [review]
Looks good kyle

**Pull request merged**
