### PR TITLE
Travis russell/edit user

### PR DESCRIPTION
**Pull request by travis-russell**
# Description

Added the edit user component.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Testing the update with postman already. Need to test this.props.location.state, BUT we first need to have front-end more built out to properly test.

- [x] Test A

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by leeformento — APPROVED** [review]
Awesome work!

**Comment by sweetooth101** [comment]
Awesome, you can see the component.

**Review by kyleteeter — APPROVED** [review]
Form fields look good. Great job!

**Review by mmeitl — APPROVED** [review]
Much needed functionality, the code looks good. Was able to modify a user upon testing.

**Pull request merged**
