### PR TITLE
Created side menu component

### PR DESCRIPTION
**Pull request by sweetooth101**
# Description

Created a side menu component, started on the layout for the dashboards side menu.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer

### CODE REVIEW

**Review by leeformento — APPROVED** [review]
Looks good Victor!

**Review by eddygonzalez9708 — CHANGES_REQUESTED** [review]
Please add detailed information about your PR in the PR template section.

**Review by travis-russell — APPROVED** [review]
looks good

**Comment by mmeitl** [comment]
Looks good

**Review by eddygonzalez9708 — APPROVED** [review]
Approved after making changes to PR template.

**Pull request merged**
