### PR TITLE
Matt meitl/workorder endpoints

### PR DESCRIPTION
**Pull request by mmeitl**
# Description

Added several work order endpoints to the api

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested that when the server started the server will produce the 'Hi' message as there is no data to test the other endpoints with yet

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by travis-russell — APPROVED** [review]
Great

**Comment by leeformento** [comment]
one approve to go! just need to add another reviewer then this should be ready to go 😄

**Review by leeformento — APPROVED** [review]
Looking good! 👍

**Review by sweetooth101 — APPROVED** [review]
looks good

**Pull request merged**
